Init setup uetk szns
AplinkosMinisterija/biip-maps-web pull request #44
Opened 2024-03-29 11:28 UTC by AndriusGeo

2024-04-18 05:29 UTC, ambrazasp requested changes

2024-04-18 05:29 UTC, ambrazasp commented on src/components/features/accordion/Szns.vue
> +      :subtitle="feature['1. Specialioji sąlyga']"
sitas su uetk layer identifikavimu neveiks

2024-04-18 05:29 UTC, ambrazasp commented on src/routes/szns/uetk.vue
> +  });
o cia tik ant uetk reik? ant szns nereik

2024-04-25 08:03 UTC, AndriusGeo commented on src/routes/szns/uetk.vue
> +}
isPreview.value ir isScreenshot - nebus naudojamas šiame view'e, todėl pašalinau.

2024-04-25 08:04 UTC, AndriusGeo commented on src/routes/szns/uetk.vue
> +    });
Pakeitime realizavau, kad apjungtų tiek grąžinamus properties, tiek geometriją ir atvaizduotų iš skirtingų sluoksnių.

2024-04-25 08:04 UTC, AndriusGeo commented on src/routes/szns/uetk.vue
> +  await mapLayers.zoomNew(sznsUetkService.id, { addStroke: true, filters });
Pakorevau.

2024-04-25 08:05 UTC, AndriusGeo commented on src/routes/szns/uetk.vue
> +  });
Taikoma tik UETK, nes SŽNS pagal cadastralId yra labai daug duomenų (pvz. Nemuno bus objektų šimtais ir jie bus labai, labai dideli), todėl ši vieta skirta tik priartinti prie reikiamo UETK objekto.

2024-05-02 08:46 UTC, ambrazasp approved these changes

2024-05-02 08:50 UTC, merged